#!/usr/bin/env bash
# This script displays the username, user ID, and home directory path from the /etc/passwd file

while IFS=: read -r username _ uid _ _ home_directory _
do
  echo "Username: $username, User ID: $uid, Home Directory: $home_directory"
done < /etc/passwd
