#!/usr/bin/env bash
# This script displays the content of the /etc/passwd file in a specified format

while IFS=: read -r username password uid gid full_name home_directory shell
do
  echo "The user $username is part of the $gid gang, lives in $home_directory and rides $shell. USER ID's place is protected by the passcode $password, more info about the user here: $full_name"
done < /etc/passwd
