#!/usr/bin/env bash
# This is a script that loops from 1 to 10 and displays "bad luck" for the 4th iteration displays "good luck" for the 8th iteration and displays "Best SChool" for other iterations
counter=1
while [ $counter -le 10 ]
do
if [ $counter -eq 4 ]
then 
echo "bad luck"
elif [ $counter -eq 8 ]
then
echo "good luck"
else 
echo "Best School"
fi
((counter++))
done
