#!/usr/bin/env bash
# This script displays content of the currect directory in a list format where only the part of the name after the dash is displayed
for file in *; do
if [[ -f $file ]] && [[ $file != .* ]]; then
new_name="{$file#*}"
echo "$new_name"
fi
done
